### PR TITLE
Add 'vildt' interpretation

### LINKED ISSUE #15: ISS added new game meat icon 'vildt'
For week 49, ISS have now introduced a game meat icon called 'vildt.png' (see attached image).

We should introduce a mapping for this in the bot postings and potentially a giphy section.
image

### PR DESCRIPTION
**Pull request by ChristianMP**
ISS introduced a new game meat icon; 'vildt'. Ensure that we properly translate that with icon and GIFs.

- Use ':deer:' icon when ISS indicates 'vildt'
- Add an inital GIF for the venison category.

resolves #15

### CODE REVIEW

**Comment by ChristianMP** [comment]
image

**Comment by danchr** [comment]
Haven't look at the code yet, but two thoughts:

1) Can we change it so that an unknown icon _doesn't_ fall back to vegetarian?
2) Can we add the current menu as a fixture to the repository? This would make it easier to add proper tests in the future.

**Review by danchr — APPROVED** [review]
SHIP IT!!!!!!

**Review by ZbigniewFigas — APPROVED** [review]

**Comment by ChristianMP** [comment]
> Haven't look at the code yet, but two thoughts:
> 
> 1. Can we change it so that an unknown icon _doesn't_ fall back to vegetarian?
> 2. Can we add the current menu as a fixture to the repository? This would make it easier to add proper tests in the future.

We made it so it falled back to vegetarian, as that's usually the case.

Alternatively it needs to be made into not falling back if it sees an icon it just doesn't recognise, but that's a bit of scope creep for this quick fix.

**Comment by ChristianMP** [comment]
I've created #17 for writing up a proper test menu for future reference.

**Pull request merged**
